export const ledgerAdjustmentExecuteLiveSmokeContract = {
  forbiddenSensitiveMarkers: [
    "Authorization",
    "Cookie",
    "token",
    "credential",
    "operation_key",
    "raw metadata",
    "raw executor error detail",
    "dedupe material",
  ],
  markers: {
    contractCheckNetworkCall: "contract_check_network_call",
    dryRunFresh: "fresh_dry_run",
    executeContractMode: "execute_contract_mode",
    executeEndpoint: "execute_endpoint",
    executeOutcome: "execute_outcome",
    executeResultFresh: "execute_result_fresh",
    executeWriteNetworkCall: "execute_write_network_call",
    ledgerEntriesRefreshAfterExecute: "ledger_entries_refresh_after_execute",
  },
  refreshStatuses: {
    error: "error",
    success: "success",
  },
  selectors: {
    contractCheckFresh: "ledger-adjustment-contract-check-fresh",
    contractCheckNetworkCall: "ledger-adjustment-contract-check-network-call",
    executeButton: "ledger-adjustment-execute-button",
    executeContractButton: "ledger-adjustment-execute-contract-button",
    executeContractMode: "ledger-adjustment-execute-contract-mode",
    executeEndpoint: "ledger-adjustment-execute-endpoint",
    executeFlags: "ledger-adjustment-execute-flags",
    executeOutcome: "ledger-adjustment-execute-outcome",
    executeResultFresh: "ledger-adjustment-execute-result-fresh",
    executeWriteNetworkCall: "ledger-adjustment-execute-write-network-call",
    ledgerRefreshStatus: "ledger-adjustment-ledger-refresh-status",
    readiness: "ledger-adjustment-execute-readiness",
    dryRunFresh: "ledger-adjustment-dry-run-fresh",
  },
  statuses: {
    applied: "applied",
    blocked: "blocked",
    dryRunRequired: "dry run required",
    executePreflight: "execute preflight",
    failed: "failed",
    idempotent: "idempotent",
    stalePlan: "stale plan",
  },
} as const;

export type LedgerAdjustmentExecuteLiveSmokeContract = typeof ledgerAdjustmentExecuteLiveSmokeContract;
