create table if not exists payment_orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  currency text not null,
  amount numeric(20, 8) not null,
  status text not null,
  source text not null,
  external_reference_id text null,
  idempotency_key_hash text not null,
  payment_intent_id uuid null,
  payment_capture_id uuid null,
  invoice_id uuid null,
  credit_grant_id uuid null,
  ledger_entry_id uuid null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, idempotency_key_hash),
  unique (tenant_id, source, external_reference_id),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, credit_grant_id) references credit_grants(tenant_id, id),
  foreign key (tenant_id, ledger_entry_id) references ledger_entries(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (amount > 0),
  check (status in ('created', 'pending_payment', 'paid', 'cancelled', 'expired', 'refunded', 'failed')),
  check (length(btrim(source)) > 0),
  check (length(btrim(idempotency_key_hash)) > 0),
  check (external_reference_id is null or length(btrim(external_reference_id)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_orders_wallet_status_created
  on payment_orders(tenant_id, wallet_id, status, created_at desc);

create table if not exists payment_intents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  order_id uuid not null,
  provider text not null,
  provider_reference_hash text not null,
  provider_reference_redacted text not null,
  currency text not null,
  amount numeric(20, 8) not null,
  status text not null,
  idempotency_key_hash text not null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, idempotency_key_hash),
  unique (tenant_id, provider, provider_reference_hash),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (amount > 0),
  check (status in ('intent_created', 'provider_handoff', 'captured', 'cancelled', 'refunded', 'failed')),
  check (length(btrim(provider)) > 0),
  check (length(btrim(provider_reference_hash)) > 0),
  check (length(btrim(provider_reference_redacted)) > 0),
  check (length(btrim(idempotency_key_hash)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_intents_order_created
  on payment_intents(tenant_id, order_id, created_at desc);

create table if not exists payment_captures (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  order_id uuid not null,
  payment_intent_id uuid not null,
  provider_reference_hash text not null,
  provider_reference_redacted text not null,
  currency text not null,
  amount numeric(20, 8) not null,
  status text not null,
  idempotency_key_hash text not null,
  credit_grant_id uuid null,
  ledger_entry_id uuid null,
  invoice_id uuid null,
  receipt_id uuid null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, idempotency_key_hash),
  unique (tenant_id, payment_intent_id, provider_reference_hash),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, payment_intent_id) references payment_intents(tenant_id, id),
  foreign key (tenant_id, credit_grant_id) references credit_grants(tenant_id, id),
  foreign key (tenant_id, ledger_entry_id) references ledger_entries(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (amount > 0),
  check (status in ('captured', 'replayed', 'refused')),
  check (length(btrim(provider_reference_hash)) > 0),
  check (length(btrim(provider_reference_redacted)) > 0),
  check (length(btrim(idempotency_key_hash)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_captures_order_created
  on payment_captures(tenant_id, order_id, created_at desc);

create table if not exists invoices (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  order_id uuid not null,
  payment_capture_id uuid null,
  invoice_number text not null,
  currency text not null,
  total_amount numeric(20, 8) not null,
  status text not null,
  line_items jsonb not null default '[]'::jsonb,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, invoice_number),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, payment_capture_id) references payment_captures(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (total_amount > 0),
  check (status in ('draft', 'issued', 'paid', 'voided', 'refunded')),
  check (length(btrim(invoice_number)) > 0),
  check (jsonb_typeof(line_items) = 'array'),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_invoices_order_created
  on invoices(tenant_id, order_id, created_at desc);

create table if not exists invoice_receipts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  invoice_id uuid not null,
  payment_capture_id uuid not null,
  receipt_number text not null,
  currency text not null,
  total_amount numeric(20, 8) not null,
  status text not null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, receipt_number),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, invoice_id) references invoices(tenant_id, id),
  foreign key (tenant_id, payment_capture_id) references payment_captures(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (total_amount > 0),
  check (status in ('issued', 'voided', 'refunded')),
  check (length(btrim(receipt_number)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create table if not exists payment_refunds (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  order_id uuid not null,
  payment_capture_id uuid not null,
  currency text not null,
  amount numeric(20, 8) not null,
  status text not null,
  reason text not null,
  idempotency_key_hash text not null,
  credit_grant_id uuid null,
  ledger_entry_id uuid null,
  reversal_ledger_entry_id uuid null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, idempotency_key_hash),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, payment_capture_id) references payment_captures(tenant_id, id),
  foreign key (tenant_id, credit_grant_id) references credit_grants(tenant_id, id),
  foreign key (tenant_id, ledger_entry_id) references ledger_entries(tenant_id, id),
  foreign key (tenant_id, reversal_ledger_entry_id) references ledger_entries(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (amount > 0),
  check (status in ('refunded', 'replayed', 'refused')),
  check (length(btrim(reason)) > 0),
  check (length(btrim(idempotency_key_hash)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_refunds_capture_created
  on payment_refunds(tenant_id, payment_capture_id, created_at desc);

create table if not exists payment_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid null,
  order_id uuid null,
  payment_intent_id uuid null,
  payment_capture_id uuid null,
  event_type text not null,
  outcome text not null,
  refusal_code text null,
  idempotency_key_hash text null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, payment_intent_id) references payment_intents(tenant_id, id),
  foreign key (tenant_id, payment_capture_id) references payment_captures(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (event_type in ('order_create', 'provider_handoff', 'capture_confirm', 'refund', 'refusal', 'reconciliation')),
  check (outcome in ('applied', 'replayed', 'refused', 'matched')),
  check (refusal_code is null or length(btrim(refusal_code)) > 0),
  check (idempotency_key_hash is null or length(btrim(idempotency_key_hash)) > 0),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_events_order_created
  on payment_events(tenant_id, order_id, created_at desc);

create table if not exists payment_reconciliations (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  project_id uuid null,
  wallet_id uuid not null,
  order_id uuid not null,
  payment_capture_id uuid null,
  invoice_id uuid null,
  ledger_entry_id uuid null,
  refund_id uuid null,
  currency text not null,
  payment_amount numeric(20, 8) not null,
  invoice_amount numeric(20, 8) not null,
  ledger_amount numeric(20, 8) not null,
  status text not null,
  audit_id uuid null,
  request_summary jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, project_id) references projects(tenant_id, id),
  foreign key (tenant_id, wallet_id) references wallets(tenant_id, id),
  foreign key (tenant_id, order_id) references payment_orders(tenant_id, id),
  foreign key (tenant_id, payment_capture_id) references payment_captures(tenant_id, id),
  foreign key (tenant_id, invoice_id) references invoices(tenant_id, id),
  foreign key (tenant_id, ledger_entry_id) references ledger_entries(tenant_id, id),
  foreign key (tenant_id, refund_id) references payment_refunds(tenant_id, id),
  foreign key (tenant_id, audit_id) references audit_logs(tenant_id, id),
  check (currency ~ '^[A-Z][A-Z0-9_]{2,31}$'),
  check (status in ('matched', 'mismatch', 'refused')),
  check (jsonb_typeof(request_summary) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_payment_reconciliations_order_created
  on payment_reconciliations(tenant_id, order_id, created_at desc);
